-- Creates the tables needed in the DW schema

-- DROP'S

-- DIMENSIONS
DROP TABLE IF EXISTS [dw].[DIM_PROJETO];
DROP TABLE IF EXISTS [dw].[DIM_ESTADO];
DROP TABLE IF EXISTS [dw].[DIM_CALENDARIO];
DROP TABLE IF EXISTS [dw].[DIM_TAREFA];
DROP TABLE IF EXISTS [dw].[DIM_FUNCIONARIO];
DROP TABLE IF EXISTS [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_PROJETO];
DROP TABLE IF EXISTS [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_TAREFA];

-- FACTS
DROP TABLE IF EXISTS [dw].[FACTO_PROJETO];
DROP TABLE IF EXISTS [dw].[FACTO_TAREFA];

-- CREATE'S

-- DIMENSIONS
CREATE TABLE [dw].[DIM_PROJETO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[CodigoProjeto] [nvarchar](50) NOT NULL,
	[Departamento] [nvarchar](200) NOT NULL,
	[Area] [nvarchar](200) NOT NULL,
	[HorasPrevistas] [int] NOT NULL,
);

CREATE TABLE [dw].[DIM_ESTADO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Estado] [nvarchar](200) NOT NULL,
);

CREATE TABLE [dw].[DIM_CALENDARIO](
	[ID] [int] NOT NULL PRIMARY KEY, -- colocar ID desta forma 202001
	[Mes] [int] NOT NULL, -- 1
	[Mes Abrev] [nvarchar](3) NOT NULL, -- Jan
	[Mes Extenso] [nvarchar](20) NOT NULL, -- Janeiro
    [Ano] [int] NOT NULL, -- 2020
	[AnoMesNum] [int] NOT NULL, -- 202001
	[MesEAno] [nvarchar](10) NOT NULL, --Jan 2020
	[TrimestreNum] [int] NOT NULL, -- 1
	[Trimestre] [nvarchar](10) NOT NULL, -- 2020 trimestre 1
);

CREATE TABLE [dw].[DIM_TAREFA](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Nome] [nvarchar](200) NOT NULL,
	[Perfil] [nvarchar](200) NOT NULL,
	[HorasPrevistas] [int] NOT NULL,
);

CREATE TABLE [dw].[DIM_FUNCIONARIO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Nome] [nvarchar](200) NOT NULL,  --USERNAME
);

CREATE TABLE [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_PROJETO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Nome] [nvarchar](20) NOT NULL,
);

CREATE TABLE [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_TAREFA](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Nome] [nvarchar](20) NOT NULL,
);


-- FACTS

CREATE TABLE [dw].[FACTO_PROJETO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Avanco] [numeric](18, 2) NOT NULL,
	[HorasRealizadas] [int] NOT NULL,
	[FK_Estado] [int] NOT NULL,
	[FK_Projeto] [int] NOT NULL,
	[FK_Calendario] [int] NOT NULL,
	[FK_Classificacao_Produtividade_Projeto] [int] NOT NULL,
);

CREATE TABLE [dw].[FACTO_TAREFA](
	[ID] [int] NOT NULL PRIMARY KEY,
	[HorasRealizadas] [int] NOT NULL,
	[FK_Projeto] [int] NOT NULL,
	[FK_Calendario] [int] NOT NULL,
	[FK_Tarefa] [int] NOT NULL,
	[FK_Funcionario] [int] NOT NULL,
	[FK_Classificacao_Produtividade_Tarefa] [int] NOT NULL,
);

/* Foreign keys are not needed, because it is a controlled environment and the definition of foreign keys would affect performance
Anyway, I decided to leave it in a comment in case it is necessary for error detection

-- PROJECT FOREIGN KEYS
-- Estado
GO
ALTER TABLE [dw].[FACTO_PROJETO] 
ADD CONSTRAINT [FK_FACTO_PROJETO_DIM_ESTADO] FOREIGN KEY ([FK_ESTADO_PROJETO])
REFERENCES [dw].[DIM_ESTADO]([ID])

-- Projeto
GO
ALTER TABLE [dw].[FACTO_PROJETO]
ADD CONSTRAINT [FK_FACTO_PROJETO_DIM_PROJETO] FOREIGN KEY ([FK_PROJETO_PROJETO])
REFERENCES [dw].[DIM_PROJETO]([ID])

-- Calendario
GO
ALTER TABLE [dw].[FACTO_PROJETO]
ADD CONSTRAINT [FK_FACTO_PROJETO_DIM_CALENDARIO] FOREIGN KEY ([FK_CALENDARIO_PROJETO])
REFERENCES [dw].[DIM_CALENDARIO]([ID])

-- Classificação Produtividade
GO
ALTER TABLE [dw].[FACTO_PROJETO]
ADD CONSTRAINT [FK_FACTO_PROJETO_DIM_CLASSIFICACAO_PRODUTIVIDADE_PROJETO] FOREIGN KEY ([FK_CLASSIFICACAO_PRODUTIVIDADE_PROJETO])
REFERENCES [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_PROJETO]([ID])


-- TASK FOREIGN KEYS
-- Projeto
GO
ALTER TABLE [dw].[FACTO_TAREFA]
ADD CONSTRAINT [FK_FACTO_TAREFA_DIM_PROJETO] FOREIGN KEY ([FK_PROJETO_TAREFA])
REFERENCES [dw].[DIM_PROJETO]([ID])

-- Calendario
GO
ALTER TABLE [dw].[FACTO_TAREFA]
ADD CONSTRAINT [FK_FACTO_TAREFA_DIM_CALENDARIO] FOREIGN KEY ([FK_CALENDARIO_TAREFA])
REFERENCES [dw].[DIM_CALENDARIO]([ID])

-- Tarefa
GO
ALTER TABLE [dw].[FACTO_TAREFA]
ADD CONSTRAINT [FK_FACTO_TAREFA_DIM_TAREFA] FOREIGN KEY ([FK_TAREFA_TAREFA])
REFERENCES [dw].[DIM_TAREFA] ([ID])

-- Funcionario
GO
ALTER TABLE [dw].[FACTO_TAREFA]
ADD CONSTRAINT [FK_FACTO_TAREFA_DIM_FUNCIONARIO] FOREIGN KEY ([FK_FUNCIONARIO_TAREFA])
REFERENCES [dw].[DIM_FUNCIONARIO]([ID])

-- Classificação Produtividade
GO
ALTER TABLE [dw].[FACTO_TAREFA]
ADD CONSTRAINT [FK_FACTO_TAREFA_DIM_CLASSIFICACAO_PRODUTIVIDADE_TAREFA] FOREIGN KEY ([FK_CLASSIFICACAO_PRODUTIVIDADE_TAREFA])
REFERENCES [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_TAREFA]([ID])

*/