-- Creates the tables needed to copy the data as is from the schema dbo to the schema stg

-- DROP'S

-- DIMENSIONS
DROP TABLE IF EXISTS [dw].[DIM_PROJETO];
DROP TABLE IF EXISTS [dw].[DIM_ESTADO];
DROP TABLE IF EXISTS [dw].[DIM_CALENDARIO];
DROP TABLE IF EXISTS [dw].[DIM_TAREFA];
DROP TABLE IF EXISTS [dw].[DIM_FUNCIONARIO];
DROP TABLE IF EXISTS [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_PROJETO];
DROP TABLE IF EXISTS [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_TAREFA];

-- FACTS
DROP TABLE IF EXISTS [dw].[FACTO_PROJETO];
DROP TABLE IF EXISTS [dw].[FACTO_TAREFA];

-- CREATE'S

-- DIMENSIONS
CREATE TABLE [dw].[DIM_PROJETO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[CodigoProjeto] [nvarchar](50) NOT NULL,
	[Departamento] [nvarchar](200) NOT NULL,
	[Area] [nvarchar](200) NOT NULL,
);

CREATE TABLE [dw].[DIM_ESTADO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Estado] [nvarchar](200) NOT NULL,
);

CREATE TABLE [dw].[DIM_CALENDARIO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Mes] [int] NOT NULL, --1
	[Mes Abrev] [nvarchar](3) NOT NULL, -- Jan
	[Mes Extenso] [nvarchar](20) NOT NULL, -- Janeiro
    [Ano] [int] NOT NULL, -- 2020
	[AnoMesNum] [int] NOT NULL, -- 202001
	[MesEAno] [nvarchar](10) NOT NULL, --Jan 2020
	[TrimestreNum] [int] NOT NULL, -- 1
	[Trimestre] [nvarchar](10) NOT NULL, -- 2020 trimestre 1
);

CREATE TABLE [dw].[DIM_TAREFA](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Nome] [nvarchar](200) NOT NULL,
	[HorasPrevistas] [int] NOT NULL,
);

CREATE TABLE [dw].[DIM_FUNCIONARIO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Nome] [nvarchar](200) NOT NULL,  --USERNAME
	[Perfil] [nvarchar](200) NOT NULL,
);

CREATE TABLE [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_PROJETO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Nome] [nvarchar](20) NOT NULL,
);

CREATE TABLE [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_TAREFA](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Nome] [nvarchar](20) NOT NULL,
);


-- FACTS

CREATE TABLE [dw].[FACTO_PROJETO](
	[ID] [int] NOT NULL PRIMARY KEY,
	[Avanco] [numeric](18, 2) NOT NULL,
	[FK_Estado] [int] NOT NULL,
	[FK_Projeto] [int] NOT NULL,
	[FK_Calendario] [int] NOT NULL,
	[FK_Classificacao_Produtividade_Projeto] [int] NOT NULL,
);

CREATE TABLE [dw].[FACTO_TAREFA](
	[ID] [int] NOT NULL PRIMARY KEY,
	[HorasRealizadas] [int] NOT NULL,
	[FK_Projeto] [int] NOT NULL,
	[FK_Calendario] [int] NOT NULL,
	[FK_Tarefa] [int] NOT NULL,
	[FK_Funcionario] [int] NOT NULL,
	[FK_Classificacao_Produtividade_Tarefa] [int] NOT NULL,
);

-- PROJECT FOREIGN KEYS
-- Estado
GO
ALTER TABLE [dw].[FACTO_PROJETO]  WITH CHECK ADD  CONSTRAINT [FK_FACTO_PROJETO_DIM_ESTADO] FOREIGN KEY([FK_ESTADO])
REFERENCES [dw].[DIM_ESTADO] ([ID])
GO
ALTER TABLE [dw].[FACTO_PROJETO] CHECK CONSTRAINT [FK_FACTO_PROJETO_DIM_ESTADO]
-- Projeto
GO
ALTER TABLE [dw].[FACTO_PROJETO]  WITH CHECK ADD  CONSTRAINT [FK_FACTO_PROJETO_DIM_PROJETO] FOREIGN KEY([FK_PROJETO])
REFERENCES [dw].[DIM_PROJETO] ([ID])
GO
ALTER TABLE [dw].[FACTO_PROJETO] CHECK CONSTRAINT [FK_FACTO_PROJETO_DIM_PROJETO]
-- Calendario
GO
ALTER TABLE [dw].[FACTO_PROJETO]  WITH CHECK ADD  CONSTRAINT [FK_FACTO_PROJETO_DIM_CALENDARIO] FOREIGN KEY([FK_Calendario])
REFERENCES [dw].[DIM_CALENDARIO] ([ID])
GO
ALTER TABLE [dw].[FACTO_PROJETO] CHECK CONSTRAINT [FK_FACTO_PROJETO_DIM_CALENDARIO]
-- Classificação Produtividade
GO
ALTER TABLE [dw].[FACTO_PROJETO]  WITH CHECK ADD  CONSTRAINT [FK_FACTO_PROJETO_DIM_CLASSIFICACAO_PRODUTIVIDADE_PROJETO] FOREIGN KEY([FK_Classificacao_Produtividade])
REFERENCES [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_PROJETO] ([ID])
GO
ALTER TABLE [dw].[FACTO_PROJETO] CHECK CONSTRAINT [FK_FACTO_PROJETO_DIM_CLASSIFICACAO_PRODUTIVIDADE_PROJETO]

-- TASK FOREIGN KEYS
-- Projeto
GO
ALTER TABLE [dw].[FACTO_TAREFA]  WITH CHECK ADD  CONSTRAINT [FK_FACTO_TAREFA_DIM_PROJETO] FOREIGN KEY([FK_PROJETO])
REFERENCES [dw].[DIM_PROJETO] ([ID])
GO
ALTER TABLE [dw].[FACTO_TAREFA] CHECK CONSTRAINT [FK_FACTO_TAREFA_DIM_PROJETO]
-- Calendario
GO
ALTER TABLE [dw].[FACTO_TAREFA]  WITH CHECK ADD  CONSTRAINT [FK_FACTO_TAREFA_DIM_CALENDARIO] FOREIGN KEY([FK_Calendario])
REFERENCES [dw].[DIM_CALENDARIO] ([ID])
GO
ALTER TABLE [dw].[FACTO_TAREFA] CHECK CONSTRAINT [FK_FACTO_TAREFA_DIM_CALENDARIO]
-- Tarefa
GO
ALTER TABLE [dw].[FACTO_TAREFA]  WITH CHECK ADD  CONSTRAINT [FK_FACTO_TAREFA_DIM_TAREFA] FOREIGN KEY([FK_Tarefa])
REFERENCES [dw].[DIM_TAREFA] ([ID])
GO
ALTER TABLE [dw].[FACTO_TAREFA] CHECK CONSTRAINT [FK_FACTO_TAREFA_DIM_TAREFA]
-- Funcionario
GO
ALTER TABLE [dw].[FACTO_TAREFA]  WITH CHECK ADD  CONSTRAINT [FK_FACTO_TAREFA_DIM_FUNCIONARIO] FOREIGN KEY([FK_Funcionario])
REFERENCES [dw].[DIM_FUNCIONARIO] ([ID])
GO
ALTER TABLE [dw].[FACTO_TAREFA] CHECK CONSTRAINT [FK_FACTO_TAREFA_DIM_FUNCIONARIO]
-- Classificação Produtividade
GO
ALTER TABLE [dw].[FACTO_TAREFA]  WITH CHECK ADD  CONSTRAINT [FK_FACTO_TAREFA_DIM_CLASSIFICACAO_PRODUTIVIDADE_TAREFA] FOREIGN KEY([FK_Classificacao_Produtividade])
REFERENCES [dw].[DIM_CLASSIFICACAO_PRODUTIVIDADE_TAREFA] ([ID])
GO
ALTER TABLE [dw].[FACTO_TAREFA] CHECK CONSTRAINT [FK_FACTO_TAREFA_DIM_CLASSIFICACAO_PRODUTIVIDADE_TAREFA]